<?php

namespace Mw\Bundle\RestBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Fetch article by id
     *
     * @param int $id
     * @return bool
     */
    public function findOneById($id) {

        $results = $this->_em->getRepository('MwRestBundle:Article')
            ->findOneBy(array('id' => $id));

        if($results)
            return true;
        return false;
    }
}
