article:
    path:     /
    defaults: { _controller: "MwRestBundle:Article:index" }

article_show:
    path:     /{id}/show
    defaults: { _controller: "MwRestBundle:Article:show" }

article_new:
    path:     /new
    defaults: { _controller: "MwRestBundle:Article:new" }

article_create:
    path:     /create
    defaults: { _controller: "MwRestBundle:Article:create" }
    methods:  POST

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "MwRestBundle:Article:edit" }

article_update:
    path:     /{id}/update
    defaults: { _controller: "MwRestBundle:Article:update" }
    methods:  [POST, PUT]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "MwRestBundle:Article:delete" }
    methods:  [POST, DELETE]
